# Generated by Django 6.0.1 on 2026-02-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
