# Generated by Django 6.0.1 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
