# Generated by Django 6.0.1 on 2026-02-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_work_show_on_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['created_at']},
        ),
    ]
